<a href="https://colab.research.google.com/github/Ayushman2005-cmyk/DMPM_EXPERIMENTS/blob/main/DMPM_LAB3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
arr = np.array([10,20,30,40,50])
print(arr.mean(),arr.sum(),arr.max(),arr.min())
print(arr.shape)

30.0 150 50 10
(5,)


In [3]:
matrix = np.array([[1,2,3],[4,5,6]])
print(matrix)
print(matrix.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [5]:
import numpy as np
arr1 = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr2 = np.ones((2, 2, 3)) * 2
print("Array A:")
print(arr1)
print("Shape:", arr1.shape)
addition = arr1 + arr2
subtraction = arr1 - arr2
division = arr1 / arr2
print("Addition (A + 2):")
print(addition)
print("Subtraction (A - 2):")
print(subtraction)
print("Division (A / 2):")
print(division)

Array A:
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
Shape: (2, 2, 3)
Addition (A + 2):
[[[ 3.  4.  5.]
  [ 6.  7.  8.]]

 [[ 9. 10. 11.]
  [12. 13. 14.]]]
Subtraction (A - 2):
[[[-1.  0.  1.]
  [ 2.  3.  4.]]

 [[ 5.  6.  7.]
  [ 8.  9. 10.]]]
Division (A / 2):
[[[0.5 1.  1.5]
  [2.  2.5 3. ]]

 [[3.5 4.  4.5]
  [5.  5.5 6. ]]]


In [6]:
import numpy as np
print(f"Statistics for arr1:")
print(f"Average (Mean): {np.mean(arr1)}")
print(f"Maximum Value: {np.max(arr1)}")
print(f"Minimum Value: {np.min(arr1)}")
print(f"Standard Deviation: {np.std(arr1)}")

Statistics for arr1:
Average (Mean): 6.5
Maximum Value: 12
Minimum Value: 1
Standard Deviation: 3.452052529534663


In [7]:
import pandas as pd
import seaborn as sns
df = sns.load_dataset('iris')
print("First 5 records:")
display(df.head())
print("\nLast 5 records:")
display(df.tail())
print("\nDataset Information:")
df.info()
print("\nStatistical Summary:")
display(df.describe())

First 5 records:


,sepal_length,sepal_width,petal_length,petal_width,species
0,5.1,3.5,1.4,0.2,setosa
1,4.9,3.0,1.4,0.2,setosa
2,4.7,3.2,1.3,0.2,setosa
3,4.6,3.1,1.5,0.2,setosa
4,5.0,3.6,1.4,0.2,setosa



Last 5 records:


,sepal_length,sepal_width,petal_length,petal_width,species
145,6.7,3.0,5.2,2.3,virginica
146,6.3,2.5,5.0,1.9,virginica
147,6.5,3.0,5.2,2.0,virginica
148,6.2,3.4,5.4,2.3,virginica
149,5.9,3.0,5.1,1.8,virginica



Dataset Information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB

Statistical Summary:


,sepal_length,sepal_width,petal_length,petal_width
count,150.000000,150.000000,150.000000,150.000000
mean,5.843333,3.057333,3.758000,1.199333
std,0.828066,0.435866,1.765298,0.762238
min,4.300000,2.000000,1.000000,0.100000
25%,5.100000,2.800000,1.600000,0.300000
50%,5.800000,3.000000,4.350000,1.300000
75%,6.400000,3.300000,5.100000,1.800000
max,7.900000,4.400000,6.900000,2.500000
