<a href="https://colab.research.google.com/github/Ayushman2005-cmyk/DMPM_EXPERIMENTS/blob/main/DMPM_LAB3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
arr = np.array([10,20,30,40,50])
print(arr.mean(),arr.sum(),arr.max(),arr.min())
print(arr.shape)

30.0 150 50 10
(5,)


In [3]:
matrix = np.array([[1,2,3],[4,5,6]])
print(matrix)
print(matrix.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [5]:
import numpy as np
arr1 = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr2 = np.ones((2, 2, 3)) * 2
print("Array A:")
print(arr1)
print("Shape:", arr1.shape)
addition = arr1 + arr2
subtraction = arr1 - arr2
division = arr1 / arr2
print("Addition (A + 2):")
print(addition)
print("Subtraction (A - 2):")
print(subtraction)
print("Division (A / 2):")
print(division)

Array A:
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
Shape: (2, 2, 3)
Addition (A + 2):
[[[ 3.  4.  5.]
  [ 6.  7.  8.]]

 [[ 9. 10. 11.]
  [12. 13. 14.]]]
Subtraction (A - 2):
[[[-1.  0.  1.]
  [ 2.  3.  4.]]

 [[ 5.  6.  7.]
  [ 8.  9. 10.]]]
Division (A / 2):
[[[0.5 1.  1.5]
  [2.  2.5 3. ]]

 [[3.5 4.  4.5]
  [5.  5.5 6. ]]]
